logging:
  level:
    tk.mybatis: DEBUG
    com.github.wxiaoqi.security.kx.kuaixiu: DEBUG
spring:
  application:
    name: spider
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/spider_test?useUnicode=true&characterEncoding=UTF8
    username: root
    password: password
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: 7777


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yusk.spider.entity